package lphy.core.model.component;

import lphy.core.model.annotation.Citation;
import lphy.core.model.annotation.GeneratorInfo;
import lphy.core.model.component.argument.ArgumentUtils;
import lphy.core.model.component.argument.ParameterInfo;
import lphy.core.narrative.Narrative;
import lphy.core.narrative.NarrativeUtils;
import lphy.core.parser.function.ExpressionNode;

import java.lang.annotation.Annotation;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import static lphy.core.model.component.GeneratorUtils.*;

/**
 * A generator generates values, either deterministically (DeterministicFunction) or stochastically (GenerativeDistribution).
 * A generator also takes named Parameters which are themselves Values, which may have been generated by a Generator.
 */
public interface Generator<T> extends GraphicalModelNode<T> {


    String getName();

    /**
     * @return a value generated by this generator.
     */
    Value<T> generate();

    String codeString();

    /**
     * @return the character symbol, for function '=' and for generative distribution '~'
     */
    char generatorCodeChar();

    @Override
    default List<GraphicalModelNode> getInputs() {
        return new ArrayList<>(getParams().values());
    }

    Map<String, Value> getParams();

    default String getInferenceStatement(Value value, Narrative narrative) {

        StringBuilder builder = new StringBuilder();

        builder.append("P(");

        String name = narrative.getId(value, false);

        builder.append(name);
        Map<String, Value> params = getParams();

        List<ParameterInfo> parameterInfos = getParameterInfo(0);
        int count = 0;
        for (ParameterInfo parameterInfo : parameterInfos) {
            Value v = params.get(parameterInfo.name());
            if (v != null && v.isRandom()) {

                if (count == 0) {
                    builder.append(" | ");
                } else {
                    builder.append(", ");
                }

                if (v.isAnonymous()) {
                    builder.append(parameterInfo.name());
                } else {

                    name = narrative.getId(v, false);
                    builder.append(name);
                }
                count += 1;
            }
        }
        builder.append(")");

        return builder.toString();
    }

    default String getInferenceNarrative(Value value, boolean unique, Narrative narrative) {

        String narrativeName = getNarrativeName();

        GeneratorInfo info = getGeneratorInfo(this.getClass());
        Citation cite = getCitation(this.getClass());
        String citationString = narrative.cite(cite);

        String verbClause = info != null ? info.verbClause() : "comes from";
        StringBuilder builder = new StringBuilder();
        builder.append(NarrativeUtils.getValueClause(value, unique, narrative));
        builder.append(" ");
        builder.append(verbClause);
        builder.append(" ");
        if (!(this instanceof ExpressionNode)) {
            if (this instanceof DeterministicFunction) {
                builder.append(NarrativeUtils.getDefiniteArticle(narrativeName, true));
            } else {
                builder.append(NarrativeUtils.getIndefiniteArticle(narrativeName, true));
            }
        }
        builder.append(" ");
        builder.append(narrativeName);
        if (citationString != null && citationString != "") {
            builder.append(" ");
            builder.append(citationString);
        }

        Map<String, Value> params = getParams();
        String currentVerb = "";
        List<ParameterInfo> parameterInfos = getParameterInfo(0);
        int count = 0;
        for (ParameterInfo parameterInfo : parameterInfos) {
            Value v = params.get(parameterInfo.name());
            if (v != null) {
                if (count == 0) builder.append(" ");
                if (count > 0) {
                    if (count == params.size() - 1) {
                        builder.append(" and ");
                    } else {
                        builder.append(", ");
                    }
                }
                if (!parameterInfo.verb().equals(currentVerb)) {
                    currentVerb = parameterInfo.verb();
                    builder.append(currentVerb);
                    builder.append(" ");
                }
                builder.append(NarrativeUtils.getValueClause(v, false, true, false, this, narrative));
                count += 1;
            }
        }
        builder.append(".");
        return builder.toString();
    }

    /**
     * Get the name of the type of object generated by this generator.
     * @return
     */
    default String getTypeName() {
        return getReturnType(this.getClass()).getSimpleName();
    }

    default void setParam(String paramName, Value<?> value) {

        String methodName = "set" + Character.toUpperCase(paramName.charAt(0)) + paramName.substring(1);

        try {
            Method method = getClass().getMethod(methodName, value.value().getClass());

            method.invoke(this, value.value());
        } catch (NoSuchMethodException e) {

            Method[] methods = getClass().getMethods();
            for (Method method : methods) {
                if (method.getName().equals(methodName)) {
                    try {
                        method.invoke(this, value.value());
                        break;
                    } catch (InvocationTargetException | IllegalAccessException ignored) {
                    }
                }
            }
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
    }

    default void setInput(String paramName, Value<?> value) {
        setParam(paramName, value);
        value.addOutput(this);
    }

    default void setInputs(Map<String, Value<?>> params) {
        params.forEach(this::setInput);
    }

    default String getParamName(Value value) {
        Map<String, Value> params = getParams();
        for (String key : params.keySet()) {
            if (params.get(key) == value) return key;
        }
        return null;
    }

    /**
     * @return true if any of the parameters are random variables,
     * or are themselves that result of a function with random parameters as arguments.
     */
    default boolean hasRandomParameters() {
        for (Map.Entry<String, Value> entry : getParams().entrySet()) {

            Value<?> v = entry.getValue();

            if (v == null) {
                throw new RuntimeException("Unexpected null value for param " + entry.getKey() + " in generator " + getName());
            }

            if (v.isRandom()) return true;
        }
        return false;
    }

    default String getParamName(int paramIndex, int constructorIndex) {
        return getParameterInfo(constructorIndex).get(paramIndex).name();
    }

    @Deprecated
    default String getParamName(int paramIndex) {
        return getParamName(paramIndex, 0);
    }

    default List<ParameterInfo> getParameterInfo(int constructorIndex) {
        return ArgumentUtils.getParameterInfo(this.getClass(), constructorIndex);
    }

    default Class<?> getParamType(String name) {
        return getParams().get(name).getType();
    }

    default GeneratorInfo getInfo() {

        Class<?> classElement = getClass();

        Method[] methods = classElement.getMethods();

        for (Method method : methods) {
            for (Annotation annotation : method.getAnnotations()) {
                if (annotation instanceof GeneratorInfo) {
                    return (GeneratorInfo) annotation;
                }
            }
        }
        return null;
    }

    default String getRichDescription(int index) {

        List<ParameterInfo> pInfo = getParameterInfo(index);

        Map<String, Value> paramValues = getParams();

        StringBuilder html = new StringBuilder("<html><h3>");
        html.append(getName());
        if (this instanceof GenerativeDistribution) {
            html.append(" distribution");
        }
        html.append("</h3>");
        GeneratorInfo info = getInfo();
        if (info != null) {
            html.append("<p>").append(getInfo().description()).append("</p><br>");
        }
        if (pInfo.size() > 0) {
            html.append("<p>parameters: <ul>");
            for (ParameterInfo pi : pInfo) {
                html.append("<li>").append(pi.name()).append(" (").append(paramValues.get(pi.name())).append("); <font color=\"#808080\">").append(pi.description()).append("</font></li>");
            }
            html.append("</ul></p>");
        }

        Citation citation = getCitation(this.getClass());
        if (citation != null) {
            html.append("<h3>Reference</h3>");
            html.append(citation.value());
            String url = NarrativeUtils.getURL(citation);
            if (url.length() > 0) {
                html.append("<br><a href=\"" + url + "\">" + url + "</a><br>");
            }
        }

        html.append("</html>");
        return html.toString();
    }


    /**
     * @param value
     * @return the narrative name for the given value, being a parameter of this generator.
     */
    default String getNarrativeName(Value value) {
        return getNarrativeName(getParamName(value));
    }

    /**
     * @param paramName the parameter name
     * @return the narrative name for the given parameter name.
     */
    default String getNarrativeName(String paramName) {
        List<ParameterInfo> parameterInfos = getParameterInfo(0);
        for (ParameterInfo parameterInfo : parameterInfos) {
            if (parameterInfo.name().equals(paramName)) {
                if (parameterInfo.suppressNameInNarrative()) return "";
                if (parameterInfo.narrativeName().length() > 0) {
                    return parameterInfo.narrativeName();
                }
            }
        }
        return paramName;
    }

    /**
     * @return the narrative name of this generator.
     */
    default String getNarrativeName() {
        GeneratorInfo generatorInfo = getGeneratorInfo(this.getClass());
        if (generatorInfo != null) {
            if (generatorInfo.narrativeName().length() > 0) return generatorInfo.narrativeName();
        }
        return getName();
    }

    // all other static methods mv to GeneratorUtils

    static Class<?>[] getParameterTypes(Class<? extends Generator> c, int constructorIndex) {
        return ArgumentUtils.getParameterTypes(c.getConstructors()[constructorIndex]);
    }

    static String getGeneratorHtml(Class<? extends Generator> generatorClass) {
        GeneratorInfo generatorInfo = getGeneratorInfo(generatorClass);

        List<ParameterInfo> pInfo = ArgumentUtils.getParameterInfo(generatorClass, 0);
        Class[] types = getParameterTypes(generatorClass, 0);

        // parameters
        StringBuilder signature = new StringBuilder();
        signature.append(getGeneratorName(generatorClass)).append("(");

        int count = 0;
        for (int i = 0; i < pInfo.size(); i++) {
            ParameterInfo pi = pInfo.get(i);
            if (count > 0) signature.append(", ");
            signature //.append(types[i].getSimpleName()).append(" ")
                    .append("<i>").append(pi.name()).append("</i>");
            count += 1;
        }
        signature.append(")");

        // main content
        StringBuilder html = new StringBuilder("<html><h2>");
        // check if deprecated
        Annotation a = generatorClass.getAnnotation(Deprecated.class);
        if (a != null) html.append("<s>");
        html.append(signature);
        if (a != null) html.append("</s>").append("<font color=\"#ff0000\">")
                .append(" @Deprecated").append("</font>");
        html.append("</h2>");

        if (generatorInfo != null) html.append("<p>").append(generatorInfo.description()).append("</p>");

        if (pInfo.size() > 0) {
            html.append("<h3>Parameters:</h3>").append("<ul>");
//            int count = 0;
            for (int i = 0; i < pInfo.size(); i++) {
                ParameterInfo pi = pInfo.get(i);
                html.append("<li>").append(types[i].getSimpleName()).
                        append(" <b>").append(pi.name()).append("</b>")
                        .append(" - <font color=\"#808080\">")
                        .append(pi.description()).append("</font></li>");

//                if (count > 0) signature.append(", ");
//                signature.append(new Text(types[i].getSimpleName())).append(" ").append(new BoldText(pi.name()));
//                count += 1;
            }
//            signature.append(")");
//            html.append(new Heading(signature.toString(), 2)).append("\n\n");
            html.append("</ul>");
        }

        List<String> returnType = Collections.singletonList(getReturnType(generatorClass).getSimpleName());
        if (returnType.size() > 0) {
            html.append("<h3>Return type:</h3>").append("<ul>");
            for (String itm : returnType)
                html.append("<li>").append(itm).append("</li>");
            html.append("</ul>");
        }

        Citation citation = getCitation(generatorClass);
        if (citation != null) {
            html.append("<h3>Reference</h3>");
            html.append(citation.value());
            if (!citation.value().endsWith(".")) html.append(".");
            String url = NarrativeUtils.getURL(citation);
            if (url.length() > 0)
                html.append("&nbsp;<a href=\"").append(url).append("\">").append(url).append("</a><br>");
        }

        String[] examples = getGeneratorExamples(generatorClass);
        if (examples.length > 0) {
            html.append("<h3>Examples</h3>");
            for (int i = 0; i < examples.length; i++) {
                String ex = examples[i];
                // add hyperlink
                if (ex.startsWith("http"))
                    ex = "&nbsp;<a href=\"" + ex + "\">" + ex + "</a>";
                html.append(ex);
                if (i < examples.length - 1)
                    html.append(", ");
            }
        }

        html.append("</html>");
        return html.toString();
    }

}
