<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.linguaphylo</groupId>
        <artifactId>lphy-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>lphy-base</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.github.linguaphylo</groupId>
            <artifactId>lphy</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.linguaphylo</groupId>
            <artifactId>jebl</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.mahout</groupId>
            <artifactId>mahout-math</artifactId>
            <version>0.13.0</version>
        </dependency>

        <dependency>
            <groupId>colt</groupId>
            <artifactId>colt</artifactId>
            <version>1.2.0</version>
        </dependency>

    </dependencies>

    <properties>
        <!-- Override on the command line: -Dslphy.args="examples/coalescent/hkyCoalescent.lphy" -->
        <slphy.args>--help</slphy.args>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <executable>java</executable>
                    <arguments>
                        <argument>-Xms64m</argument>
                        <argument>-Xmx5g</argument>
                        <argument>--module-path</argument>
                        <modulepath/>
                        <argument>--module</argument>
                        <argument>lphy.core/lphy.core.simulator.SLPhy</argument>
                        <argument>${slphy.args}</argument>
                    </arguments>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>