package lphy.core.model.datatype;

import lphy.core.model.DeterministicFunction;
import lphy.core.model.Value;
import lphy.phylospec.types.PrimitiveType;
import org.phylospec.types.Real;

public class RealValue extends Value<Double> implements Real, PrimitiveType<Double> {

    public RealValue(String id, Double value) {

        super(id, value);
    }

    /**
     * Constructs an anonymous Double value.
     * @param value
     */
    public RealValue(Double value) {

        super(null, value);
    }

    public RealValue(String id, Value<Double[]> value) {
        super(id, value.value()[0]);

        if (value.value().length > 1) {
            System.err.println("WARNING: ignoring all but the first element in " + (value.getId()) + " of length " + value.value().length + "!");
        }
    }

    public RealValue(String id, Double value, DeterministicFunction<Double> function) {

        super(id, value, function);
    }

    /**
     * Constructs an anonymous Double value and records the function that it was generated by
     * @param value
     * @param function
     */
    public RealValue(Double value, DeterministicFunction<Double> function) {

        super(null, value, function);
    }

    @Override
    public Double getPrimitive() {
        return value();
    }
}
