package lphy.core.model.datatype;

import lphy.core.model.DeterministicFunction;
import lphy.core.model.Value;
import org.phylospec.types.Real;

public class RealValue extends Value<Real> {

    public RealValue(String id, Real value) {

        super(id, value);
    }

    /**
     * Constructs an anonymous Double value.
     * @param value
     */
    public RealValue(Real value) {

        super(null, value);
    }

    public RealValue(String id, Value<Real[]> value) {
        super(id, value.value()[0]);

        if (value.value().length > 1) {
            System.err.println("WARNING: ignoring all but the first element in " + (value.getId()) + " of length " + value.value().length + "!");
        }
    }

    public RealValue(String id, Real value, DeterministicFunction<Real> function) {

        super(id, value, function);
    }

    /**
     * Constructs an anonymous Double value and records the function that it was generated by
     * @param value
     * @param function
     */
    public RealValue(Real value, DeterministicFunction<Real> function) {

        super(null, value, function);
    }
}
